version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
     - "5432:5432"
    volumes:
     - D:\Pessoal\Desenvolvimento\workspace_estudo\alura-nodejs-api-rest-express-mongodb\postgres\data:/var/lib/postgresql/data
    networks:
     - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge