CREATE UNIQUE INDEX COMPANY_COST_CENTRE_COST_CENTRE_LNK_ID
  ON COMPANY_COST_CENTRE (COST_CENTRE_LNK_ID);
CREATE INDEX SYS_COUNTRY_COUNTRY_CODE_ISO2
  ON SYS_COUNTRY (COUNTRY_CODE_ISO2);
CREATE UNIQUE INDEX TAX_TYPE_TAX_TYPE
  ON TAX_TYPE (TAX_TYPE);
CREATE UNIQUE INDEX "Indx-COMPANY_LOB"
  ON COMPANY_LOB (LOB_CODE_LNK_ID);
CREATE UNIQUE INDEX COMPANY_BOOK_TYPE_BOOK_TYPE_LNK_ID
  ON COMPANY_BOOK_TYPE (BOOK_TYPE_LNK_ID);
CREATE INDEX COMPANY_BOOK_COST_CENTRE_LNK_ID
  ON COMPANY_BOOK (COST_CENTRE_LNK_ID);
CREATE INDEX SYS_ADHOC_HOLIDAY_CALENDAR_CODE
  ON SYS_ADHOC_HOLIDAY (CALENDAR_CODE);
CREATE UNIQUE INDEX SYS_CALENDAR_CALENDAR_CODE
  ON SYS_CALENDAR (CALENDAR_CODE);
CREATE UNIQUE INDEX DOMS_INDUSTRY_SECTOR_TYPE_DOMAIN
  ON DOMS_INDUSTRY_SECTOR_TYPE (DOMAIN);
CREATE INDEX SYS_COUNTRY_CCY_LNK_COUNTRY_CODE_ISO2
  ON SYS_COUNTRY_CCY_LNK (COUNTRY_CODE_ISO2);
CREATE INDEX PORT_DSEC_MOV_REFERENCE_DATE
  ON PORT_DSEC_MOV (REFERENCE_DATE);
CREATE INDEX PORT_FCTY_MOV_REFERENCE_DATE
  ON PORT_FCTY_MOV (REFERENCE_DATE);
CREATE INDEX PORT_FOEX_MOV_REFERENCE_DATE
  ON PORT_FOEX_MOV (REFERENCE_DATE);
CREATE INDEX PORT_FUTU_MOV_REFERENCE_DATE
  ON PORT_FUTU_MOV (REFERENCE_DATE);
CREATE INDEX PORT_RECV_MOV_REFERENCE_DATE
  ON PORT_RECV_MOV (REFERENCE_DATE);
CREATE INDEX PORT_RECV_LNK_REFERENCE_DATE
  ON PORT_RECV_LNK (REFERENCE_DATE);
CREATE INDEX PORT_REPO_MOV_REFERENCE_DATE
  ON PORT_REPO_MOV (REFERENCE_DATE);
CREATE INDEX PORT_REPO_DET_REFERENCE_DATE
  ON PORT_REPO_DET (REFERENCE_DATE);
CREATE UNIQUE INDEX DOMS_AMORTIZING_TYPE_DOMAIN
  ON DOMS_AMORTIZING_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_BANKRUPTCY_REMOTE_DOMAIN
  ON DOMS_BANKRUPTCY_REMOTE (DOMAIN);
CREATE UNIQUE INDEX DOMS_BRANCH_SUBSIDIARY_DOMAIN
  ON DOMS_BRANCH_SUBSIDIARY (DOMAIN);
CREATE UNIQUE INDEX DOMS_BROKEN_PERIOD_TYPE_DOMAIN
  ON DOMS_BROKEN_PERIOD_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_CALC_DAY_CONVENTION_DOMAIN
  ON DOMS_CALC_DAY_CONVENTION (DOMAIN);
CREATE UNIQUE INDEX DOMS_CAP_TYPE_DOMAIN
  ON DOMS_CAP_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_CASH_FLOW_APPROACH_DOMAIN
  ON DOMS_CASH_FLOW_APPROACH (DOMAIN);
CREATE UNIQUE INDEX DOMS_CASH_FLOW_QUALITY_DOMAIN
  ON DOMS_CASH_FLOW_QUALITY (DOMAIN);
CREATE UNIQUE INDEX DOMS_CASH_FLOW_TYPE_DOMAIN
  ON DOMS_CASH_FLOW_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_CCP_EXPOSURE_TYPE_DOMAIN
  ON DOMS_CCP_EXPOSURE_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_ROLLING_CONVENTION_DOMAIN
  ON DOMS_ROLLING_CONVENTION (DOMAIN);
CREATE UNIQUE INDEX DOMS_CINST_CALC_RULE_DOMAIN
  ON DOMS_CINST_CALC_RULE (DOMAIN);
CREATE UNIQUE INDEX DOMS_CINST_RULE_ANNUITY_AFTER_MAT_DOMAIN
  ON DOMS_CINST_RULE_ANNUITY_AFTER_MAT (DOMAIN);
CREATE UNIQUE INDEX DOMS_CLIENT_PROPRIETARY_DOMAIN
  ON DOMS_CLIENT_PROPRIETARY (DOMAIN);
CREATE UNIQUE INDEX DOMS_COLLATERAL_MODE_DOMAIN
  ON DOMS_COLLATERAL_MODE (DOMAIN);
CREATE UNIQUE INDEX DOMS_COMMITTED_DOMAIN
  ON DOMS_COMMITTED (DOMAIN);
CREATE UNIQUE INDEX DOMS_CONSOLIDATION_TYPE_DOMAIN
  ON DOMS_CONSOLIDATION_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_SECURITY_STATUS_DOMAIN
  ON DOMS_SECURITY_STATUS (DOMAIN);
CREATE UNIQUE INDEX DOMS_DEFERMENT_CONTEXT_DOMAIN
  ON DOMS_DEFERMENT_CONTEXT (DOMAIN);
CREATE UNIQUE INDEX DOMS_DEFERMENT_METHOD_DOMAIN
  ON DOMS_DEFERMENT_METHOD (DOMAIN);
CREATE UNIQUE INDEX DOMS_DELIVERY_TYPE_DOMAIN
  ON DOMS_DELIVERY_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_DISTRIBUTION_CHANNEL_DOMAIN
  ON DOMS_DISTRIBUTION_CHANNEL (DOMAIN);
CREATE UNIQUE INDEX DOMS_FACILITY_LIQ_TYPE_DOMAIN
  ON DOMS_FACILITY_LIQ_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_FACILITY_TYPE_DOMAIN
  ON DOMS_FACILITY_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_FAIR_VALUE_OPTION_DOMAIN
  ON DOMS_FAIR_VALUE_OPTION (DOMAIN);
CREATE UNIQUE INDEX DOMS_BALANCE_TYPE_DOMAIN
  ON DOMS_BALANCE_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_STATEMENT_TYPE_DOMAIN
  ON DOMS_STATEMENT_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_FIXING_RULE_DOMAIN
  ON DOMS_FIXING_RULE (DOMAIN);
CREATE UNIQUE INDEX DOMS_FORBEARANCE_MEASURES_DOMAIN
  ON DOMS_FORBEARANCE_MEASURES (DOMAIN);
CREATE UNIQUE INDEX DOMS_SETTLEMENT_MODE_DOMAIN
  ON DOMS_SETTLEMENT_MODE (DOMAIN);
CREATE UNIQUE INDEX DOMS_GIVEN_RECEIVED_DOMAIN
  ON DOMS_GIVEN_RECEIVED (DOMAIN);
CREATE UNIQUE INDEX DOMS_INCOME_TYPE_DOMAIN
  ON DOMS_INCOME_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_INVPTY_STATUS_DOMAIN
  ON DOMS_INVPTY_STATUS (DOMAIN);
CREATE UNIQUE INDEX DOMS_TAX_STATUS_DOMAIN
  ON DOMS_TAX_STATUS (DOMAIN);
CREATE UNIQUE INDEX DOMS_PAY_RECEIVE_DOMAIN
  ON DOMS_PAY_RECEIVE (DOMAIN);
CREATE UNIQUE INDEX DOMS_LONG_SHORT_DOMAIN
  ON DOMS_LONG_SHORT (DOMAIN);
CREATE UNIQUE INDEX DOMS_MARGIN_EXCESS_TYPE_DOMAIN
  ON DOMS_MARGIN_EXCESS_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_MARGIN_TYPE_DOMAIN
  ON DOMS_MARGIN_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_NETTING_CLASS_DOMAIN
  ON DOMS_NETTING_CLASS (DOMAIN);
CREATE UNIQUE INDEX DOMS_OVERLAPPING_PRIORITY_DOMAIN
  ON DOMS_OVERLAPPING_PRIORITY (DOMAIN);
CREATE UNIQUE INDEX DOMS_PARTICIPATION_FLAG_DOMAIN
  ON DOMS_PARTICIPATION_FLAG (DOMAIN);
CREATE UNIQUE INDEX DOMS_CALC_DAY_RULE_DOMAIN
  ON DOMS_CALC_DAY_RULE (DOMAIN);
CREATE UNIQUE INDEX DOMS_PENALTY_CALC_METHOD_DOMAIN
  ON DOMS_PENALTY_CALC_METHOD (DOMAIN);
CREATE UNIQUE INDEX DOMS_REPARTITION_METHOD_DOMAIN
  ON DOMS_REPARTITION_METHOD (DOMAIN);
CREATE UNIQUE INDEX DOMS_SENIORITY_DOMAIN
  ON DOMS_SENIORITY (DOMAIN);
CREATE UNIQUE INDEX DOMS_SERVICING_TYPE_DOMAIN
  ON DOMS_SERVICING_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_DISCOUNT_METHOD_DOMAIN
  ON DOMS_DISCOUNT_METHOD (DOMAIN);
CREATE UNIQUE INDEX DOMS_SUB_TYPE_DOMAIN
  ON DOMS_SUB_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_TARGET_TYPE_DOMAIN
  ON DOMS_TARGET_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_TAX_INVPTY_TYPE_DOMAIN
  ON DOMS_TAX_INVPTY_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_UNDERLYING_FAMILY_DOMAIN
  ON DOMS_UNDERLYING_FAMILY (DOMAIN);
CREATE UNIQUE INDEX "Indx-INVPTY_RTNG_AGCY_RTS_STR"
  ON INVPTY_RTNG_AGCY_RTS_STR (RATING_ID);
CREATE UNIQUE INDEX DOMS_SYSTEM_TYPE_DOMAIN
  ON DOMS_SYSTEM_TYPE (DOMAIN);
CREATE UNIQUE INDEX "Indx-PRODUCT_EXT_COD"
  ON PRODUCT_EXT_COD (PRODUCT_CODE, SOURCE_SYSTEM, PRODUCT_CODE_EXT);
CREATE UNIQUE INDEX DOMS_DERIVATIVE_MULTIPLIER_TYPE_DOMAIN
  ON DOMS_DERIVATIVE_MULTIPLIER_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_PERFORMING_STATUS_DOMAIN
  ON DOMS_PERFORMING_STATUS (DOMAIN);
CREATE UNIQUE INDEX DOMS_BANKING_TRADING_DOMAIN
  ON DOMS_BANKING_TRADING (DOMAIN);
CREATE INDEX PORT_SWAP_POS_REFERENCE_DATE
  ON PORT_SWAP_POS (REFERENCE_DATE);
CREATE UNIQUE INDEX DOMS_GL_CLASS_DOMAIN
  ON DOMS_GL_CLASS (DOMAIN);
CREATE INDEX PORT_VOSTRO_POS_REFERENCE_DATE
  ON PORT_VOSTRO_POS (REFERENCE_DATE);
CREATE INDEX PORT_DSEC_POS_REFERENCE_DATE
  ON PORT_DSEC_POS (REFERENCE_DATE);
CREATE UNIQUE INDEX "Indx-PORT_FUTU_POS"
  ON PORT_FUTU_POS (REFERENCE_DATE, SOURCE_SYSTEM, PRODUCT_CODE, CONTRACT_REFERENCE, COMPANY_CODE);
CREATE INDEX PORT_FUTU_POS_REFERENCE_DATE
  ON PORT_FUTU_POS (REFERENCE_DATE);
CREATE INDEX PORT_NOSTRO_POS_REFERENCE_DATE
  ON PORT_NOSTRO_POS (REFERENCE_DATE);
CREATE INDEX PORT_REPO_POS_REFERENCE_DATE
  ON PORT_REPO_POS (REFERENCE_DATE);
CREATE INDEX PORT_FINC_POS_REFERENCE_DATE
  ON PORT_FINC_POS (REFERENCE_DATE);
CREATE INDEX PORT_RECV_POS_REFERENCE_DATE
  ON PORT_RECV_POS (REFERENCE_DATE);
CREATE INDEX PORT_SWAP_MOV_REFERENCE_DATE
  ON PORT_SWAP_MOV (REFERENCE_DATE);
CREATE INDEX PORT_NDFS_MOV_REFERENCE_DATE
  ON PORT_NDFS_MOV (REFERENCE_DATE);
CREATE INDEX PORT_NDFS_POS_REFERENCE_DATE
  ON PORT_NDFS_POS (REFERENCE_DATE);
CREATE INDEX PORT_GUAR_MOV_REFERENCE_DATE
  ON PORT_GUAR_MOV (REFERENCE_DATE);
CREATE INDEX PORT_GUAR_POS_REFERENCE_DATE
  ON PORT_GUAR_POS (REFERENCE_DATE);
CREATE INDEX PNL_GMPLEX_CLC_REFERENCE_DATE
  ON PNL_GMPLEX_CLC (REFERENCE_DATE);
CREATE INDEX PORT_FCTY_LNK_REFERENCE_DATE
  ON PORT_FCTY_LNK (REFERENCE_DATE);
CREATE INDEX PNL_FEEINC_DET_REFERENCE_DATE
  ON PNL_FEEINC_DET (REFERENCE_DATE);
CREATE INDEX PNL_OPERINC_DET_REFERENCE_DATE
  ON PNL_OPERINC_DET (REFERENCE_DATE);
CREATE INDEX MKTD_EOD_PRICE_REFERENCE_DATE
  ON MKTD_EOD_PRICE (REFERENCE_DATE);
CREATE INDEX GENLDG_BS_JOURNAL_REFERENCE_DATE
  ON GENLDG_BS_JOURNAL (REFERENCE_DATE);
CREATE INDEX GENLDG_GLBS_POS_REFERENCE_DATE
  ON GENLDG_GLBS_POS (REFERENCE_DATE);
CREATE INDEX GENLDG_GLBS_POS_SOURCE_SYSTEM
  ON GENLDG_GLBS_POS (SOURCE_SYSTEM);
CREATE INDEX GENLDG_GLBS_POS_COST_CENTRE
  ON GENLDG_GLBS_POS (COST_CENTRE);
CREATE INDEX GENLDG_GLBS_POS_GL_GAAP_CODE
  ON GENLDG_GLBS_POS (GL_GAAP_CODE);
CREATE INDEX PNL_OPERINC_CSF_LINK_REFERENCE_DATE
  ON PNL_OPERINC_CSF_LINK (REFERENCE_DATE);
CREATE INDEX PORT_REPO_CSF_REFERENCE_DATE
  ON PORT_REPO_CSF (REFERENCE_DATE);
CREATE INDEX PORT_VOSTRO_CSF_REFERENCE_DATE
  ON PORT_VOSTRO_CSF (REFERENCE_DATE);
CREATE INDEX PORT_DSEC_CSF_REFERENCE_DATE
  ON PORT_DSEC_CSF (REFERENCE_DATE);
CREATE INDEX PORT_FINC_CSF_REFERENCE_DATE
  ON PORT_FINC_CSF (REFERENCE_DATE);
CREATE INDEX PORT_NOSTRO_CSF_REFERENCE_DATE
  ON PORT_NOSTRO_CSF (REFERENCE_DATE);
CREATE INDEX PORT_SWAP_CSF_REFERENCE_DATE
  ON PORT_SWAP_CSF (REFERENCE_DATE);
CREATE INDEX PORT_FOEX_CSF_REFERENCE_DATE
  ON PORT_FOEX_CSF (REFERENCE_DATE);
CREATE INDEX PORT_RECV_CSF_REFERENCE_DATE
  ON PORT_RECV_CSF (REFERENCE_DATE);
CREATE INDEX PORT_NDFS_CSF_REFERENCE_DATE
  ON PORT_NDFS_CSF (REFERENCE_DATE);
CREATE INDEX PORT_FUTU_CSF_REFERENCE_DATE
  ON PORT_FUTU_CSF (REFERENCE_DATE);
CREATE UNIQUE INDEX "Indx-SYS_CURVE_UNDERLYING_LINK"
  ON SYS_CURVE_UNDERLYING_LINK (CURVE_NAME, UNDERLYING_CODE);
CREATE INDEX ALCM_CPAD_EAD_BASE_REFERENCE_DATE
  ON ALCM_CPAD_EAD_BASE (REFERENCE_DATE);
CREATE UNIQUE INDEX "Indx-RECON_DIMENSION"
  ON RECON_DIMENSION (RECON_METRIC_ID, PRODUCT_CODE, GL_CLASS);
CREATE UNIQUE INDEX "Indx-RECON_DIMENSION2"
  ON RECON_DIMENSION (RECON_DIMENSION_ID, RECON_DIMENSION_GROUP);
CREATE UNIQUE INDEX "Indx-RECON_GL_POINT"
  ON RECON_GL_POINT (RECON_DIMENSION_GROUP, GL_ACCOUNT_CODE);
CREATE INDEX RECON_GL_AGGREGATION_REFERENCE_DATE
  ON RECON_GL_AGGREGATION (REFERENCE_DATE);
CREATE INDEX RECON_GL_AGGREGATION_SOURCE_SYSTEM
  ON RECON_GL_AGGREGATION (SOURCE_SYSTEM);
CREATE INDEX RECON_GL_AGGREGATION_COMPANY_CODE
  ON RECON_GL_AGGREGATION (COMPANY_CODE);
CREATE INDEX RECON_GL_AGGREGATION_COST_CENTRE
  ON RECON_GL_AGGREGATION (COST_CENTRE);
CREATE INDEX RECON_GL_AGGREGATION_RECON_DIMENSION_GROUP
  ON RECON_GL_AGGREGATION (RECON_DIMENSION_GROUP);
CREATE UNIQUE INDEX "Indx-RECON_BZDF_POINT"
  ON RECON_BZDF_POINT (RECON_DIMENSION_ID, RECON_BZDF_MAP_ID);
CREATE UNIQUE INDEX "Indx-RECON_BZDF_MAP"
  ON RECON_BZDF_MAP (SOURCE_TABLE, SOURCE_TABLE_COLUMN);
CREATE UNIQUE INDEX RECON_MATH_OPERATOR_MATH_OPERATOR_ID
  ON RECON_MATH_OPERATOR (MATH_OPERATOR_ID);
CREATE INDEX RECON_BZDF_AGGREGATION_REFERENCE_DATE
  ON RECON_BZDF_AGGREGATION (REFERENCE_DATE);
CREATE INDEX RECON_BZDF_CONTRACT_LOAD_REFERENCE_DATE
  ON RECON_BZDF_CONTRACT_LOAD (REFERENCE_DATE);
CREATE INDEX PNL_INTERESTINC_CLC_REFERENCE_DATE
  ON PNL_INTERESTINC_CLC (REFERENCE_DATE);
CREATE INDEX PORT_OTHER_CSF_REFERENCE_DATE
  ON PORT_OTHER_CSF (REFERENCE_DATE);
CREATE INDEX PORT_OTHER_POS_REFERENCE_DATE
  ON PORT_OTHER_POS (REFERENCE_DATE);
CREATE UNIQUE INDEX "Indx-PRODUCT_HSBC_GRP_LINK"
  ON PRODUCT_HSBC_GRP_LINK (PRODUCT_CODE, GRP_PRODUCT_CODE, SOURCE_TABLE);
CREATE UNIQUE INDEX "Indx-TAX_FOREIGN_PERSON"
  ON TAX_FOREIGN_PERSON (ENTITY_CODE, FOREIGN_STATUS_INITIAL_DATE);
CREATE INDEX MKTD_EOD_CURVE_REFERENCE_DATE
  ON MKTD_EOD_CURVE (REFERENCE_DATE);
CREATE INDEX CRM_GUAR_POS_REFERENCE_DATE
  ON CRM_GUAR_POS (REFERENCE_DATE);
CREATE UNIQUE INDEX DOMS_UNDERLYING_CLASSIFICATION_DOMAIN
  ON DOMS_UNDERLYING_CLASSIFICATION (DOMAIN);
CREATE UNIQUE INDEX DOMS_BANKING_FACILITY_TYPE_DOMAIN
  ON DOMS_BANKING_FACILITY_TYPE (DOMAIN);
CREATE UNIQUE INDEX DOMS_FACILITY_PURPOSE_DOMAIN
  ON DOMS_FACILITY_PURPOSE (DOMAIN);
CREATE UNIQUE INDEX "Indx-INVPTY_TYPE"
  ON INVPTY_TYPE (INVPTY_TYPE);


